# -*- mode: ruby -*-

# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "dtaas"

  # gateway node - hosts traefik, dns and static client website
  config.vm.define "dtaas" do |node|
    node.vm.hostname = "foo.com" 
    node.vm.network "public_network", :bridge => 'ens10f3', :mac => "02163ef4f4f4"


   node.vm.provider "virtualbox" do |vb|
      vb.name = "DTaaSOne"
      vb.memory = 16384
      vb.cpus = 8
    end

    node.ssh.private_key_path = "vagrant"
    node.vm.provision "shell", privileged: false, path: "start.sh"
  end

end

