#!/usr/bin/env sh

TOP_DIR="$(pwd)"
export TOP_DIR

if git diff --cached --name-only | grep "^client/" >/dev/null; then
    cd client || exit
    yarn install
    yarn format && yarn syntax
else
    printf "No changes in the client directory. Skipping pre-commit hook.\n\n"
fi

cd "$TOP_DIR" || exit
if git diff --cached --name-only | grep "^servers/execution/runner/" >/dev/null; then
    cd "servers/execution/runner" || exit
    yarn install
    yarn format && yarn syntax
else
    printf "No changes in the servers/execution/runner directory. Skipping pre-commit hook.\n\n"
fi
