#!/usr/bin/env sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
TOP_DIR="$(pwd)"
export TOP_DIR

if git diff --name-only origin/"$BRANCH_NAME"...HEAD | grep "^client/" >/dev/null; then
    cd client || exit
    yarn install
    yarn jest . --coverage=false
else
    printf "No changes in the client directory. Skipping pre-push hook.\n\n"
fi

cd "$TOP_DIR" || exit
if git diff --name-only origin/"$BRANCH_NAME"...HEAD | grep "^servers/execution/runner/" >/dev/null; then
    cd "servers/execution/runner" || exit
    yarn install
    yarn test:nocov
else
    printf "No changes in the servers/execution/runner/ directory. Skipping pre-push hook.\n\n"
fi
