http:
  routers:
    dtaas:
      entryPoints:
        - http
      rule: 'Host(`foo.com`)'
      middlewares:
        - basic-auth
      service: dtaas

    user1:
      entryPoints:
        - http
      rule: 'Host(`foo.com`) && PathPrefix(`/user1`)'
      middlewares:
        - basic-auth
      service: user1

    libms:
      entryPoints:
        - http
      rule: 'Host(`foo.com`) && PathPrefix(`/lib`)'
      service: libms


  # Middleware: Basic authentication
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/auth"
        removeHeader: true


  services:
    dtaas:
      loadBalancer:
        servers:
          - url: "http://localhost:4000"

    user1:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"

    libms:
      loadBalancer:
        servers:
          - url: "http://localhost:4001"