http:
  routers:
    dtaas:
      entryPoints:
        - http
      rule: "Host(`localhost`)"
      middlewares:
        - basic-auth
      service: dtaas

    user1:
      entryPoints:
        - http
      rule: "Host(`localhost`) && PathPrefix(`/user1`)"
      middlewares:
        - basic-auth
      service: user1

    user2:
      entryPoints:
        - http
      rule: "Host(`localhost`) && PathPrefix(`/user2`)"
      middlewares:
        - basic-auth
      service: user2

    libms:
      entryPoints:
        - http
      rule: "Host(localhost`) && PathPrefix(`/lib`)"
      service: libms

  # Middleware: Basic authentication
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/auth"
        removeHeader: true

  services:
    dtaas:
      loadBalancer:
        servers:
          - url: "http://localhost:4000"

    user1:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"

    user2:
      loadBalancer:
        servers:
          - url: "http://localhost:8091"

    libms:
      loadBalancer:
        servers:
          - url: "http://localhost:4001"
