"""Manages password.env.current file"""

import logging
import os
from pathlib import Path
from dotenv import dotenv_values, set_key, unset_key
from .config import Config
from .utils import write_secret_file

logger = logging.getLogger(__name__)

PASSWORDS_FILE = "password.env.current"

# Keys belonging to each service (used by remove_service_passwords)
SERVICE_KEYS = {
    "thingsboard": [
        "TB_SYSADMIN_CURRENT_PASSWORD",
        "TB_TENANT_ADMIN_CURRENT_PASSWORD",
    ],
    "thingsboard-ce": [
        "TB_SYSADMIN_CURRENT_PASSWORD",
        "TB_TENANT_ADMIN_CURRENT_PASSWORD",
    ],
    "gitlab": [
        "GITLAB_ROOT_CURRENT_PASSWORD",
    ],
}


def _get_passwords_path() -> Path:
    """Return the path to config/current.passwords.env."""
    base_dir = Config.get_base_dir()
    return base_dir / "config" / PASSWORDS_FILE


def get_current_password(key: str, default: str = "") -> str:
    """Read a single password from current.passwords.env.

    Args:
        key: Environment variable key (e.g. TB_SYSADMIN_CURRENT_PASSWORD)
        default: Value returned when the key is missing or file absent

    Returns:
        The stored password, or *default*.
    """
    path = _get_passwords_path()
    if not path.exists():
        return default
    values = dotenv_values(path)
    return values.get(key) or default


def save_password(key: str, value: str) -> None:
    """Create or update a password entry in current.passwords.env.

    Args:
        key: Environment variable key
        value: New password value
    """
    path = _get_passwords_path()
    if not path.exists():
        write_secret_file(
            path,
            "# Auto-generated by dtaas-services. Do not edit manually.\n",
        )
    set_key(str(path), key, value)
    os.chmod(path, 0o600)
    logger.debug("Updated %s in %s", key, PASSWORDS_FILE)


def remove_service_passwords(service_name: str) -> None:
    """Remove all password entries for a given service.

    Args:
        service_name: Lowercase service name (e.g. 'thingsboard', 'gitlab')
    """
    keys = SERVICE_KEYS.get(service_name.lower(), [])
    if not keys:
        return

    path = _get_passwords_path()
    if not path.exists():
        return

    for key in keys:
        unset_key(str(path), key)
    logger.debug("Removed %s entries from %s", service_name, PASSWORDS_FILE)
