---
version: "2"
plugins:
  shellcheck:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - typescript:
        - javascript:
        - python:
        - php:
      min_tokens: 50
      max_blocks: 10
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: client/.eslintrc
  fixme:
    enabled: true
exclude_patterns:
  - "**.md"
  - "**.txt"
  - "**.json"
  - docs/
  - "**/node_modules/"
  - "**/build/"
  - "**/public/"
  - "**/coverage"
