---
version: "2"
plugins:
  shellcheck:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 55
        javascript:
        python:
        php:
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: client/.eslintrc
  fixme:
    enabled: true
exclude_patterns:
  - "**.md"
  - "**.txt"
  - "**.json"
  - docs/
  - "**/node_modules/"
  - "**/build/"
  - "**/public/"
  - "**/coverage"
  - "client/config/"
