---
version: "2"

plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
        javascript:
        python:
          python_version: 3
          mass_threshold: 7
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: .eslintrc
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true
    checks:
      python:S1542:
        enabled: false

exclude_patterns:
  - "**.txt"
  - "**.json"
  - "**/api/"
  - "**/build/"
  - "**/coverage/"
  - "**/dist/"
  - "**/node_modules/"
  - "**/public/"
  - client/config/
  - servers/lib/src/types.ts
  - "deploy/config/client/env*.js"
  - .pylintrc
