comment:
  # show component info in the PR comment
  layout: "header, diff, files, components"

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 20%
    patch:
      default:
        informational: true
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

component_management:
  individual_components:
    # this is an identifier that should not be changed
    - component_id: client_website
      # this is a display name, and can be changed freely
      name: Website
      paths:
        - client/**
    # this is an identifier that should not be changed
    - component_id: lib_ms
      # this is a display name, and can be changed freely
      name: Lib Microservice
      paths:
        - servers/lib/**
    # this is an identifier that should not be changed
    - component_id: runner
      # this is a display name, and can be changed freely
      name: Execution Runner
      paths:
        - servers/execution/**
    # this is an identifier that should not be changed
    - component_id: dtaas_cli
      # this is a display name, and can be changed freely
      name: DTaaS CLI
      paths:
        - cli/**
    # this is an identifier that should not be changed
    - component_id: dtaas_services_cli
      # this is a display name, and can be changed freely
      name: DTaaS Services CLI
      paths:
        - deploy/services/cli/**
