---
version: "2"

plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      count_threshold: 3
      languages:
        typescript:
          mass_threshold: 45
        javascript:
        python:
          python_version: 3
          mass_threshold: 40
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: .eslintrc
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true
    checks:
      python:S1542:
        enabled: false

exclude_patterns:
  - "**.json"
  - "**.txt"
  - ".pylintrc"
  - servers/lib/src/types.ts
  - "**/api/"
  - "**/build/"
  - "**/coverage/"
  - "**/dist/"
  - "**/node_modules/"
  - "**/public/"
  - "**/script/"
  - "client/config/"
  - "deploy/config/client/env*.js"
  - "files/"
  - "CODE_OF_CONDUCT.md"
  - "CONTRIBUTING.md"
  - "LICENSE.md"
  - ".github/ISSUE_TEMPLATE/"
  - "docs/developer/conduct.md"
