site_name: Digital Twin as a Service (DTaaS)

repo_url: https://github.com/into-cps-association/DTaaS
repo_name: DTaaS
copyright: Copyright &copy; 2022 - 2024 The INTO-CPS Association

theme: 
  name: material
  locale: en
  logo: assets/dtaas-logo.png
  favicon: assets/dtaas-logo.png
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.footer

nav:
  - Home: index.md
  - Admin:
      - Overview: admin/overview.md
      - Authorization:
        - Client: admin/client/auth.md
        - Servers: admin/servers/auth.md
      - Host Install:
        - Localhost: admin/localhost.md
        - Trial: admin/trial.md
        - Production: admin/host.md
      - Vagrant:
        - Base Box: admin/vagrant/base-box.md
        - Single Machine: admin/vagrant/single-machine.md
        - Two Machines: admin/vagrant/two-machines.md
      - Separate Packages:
        - Website: admin/client/CLIENT.md
        - Library microservice: admin/servers/lib/LIB-MS.md
      - Services: admin/services.md
      - Guides:
        - New user: admin/guides/add_user.md
        - New Service: admin/guides/add_service.md
        - Install Gitlab: admin/guides/gitlab.md
        - Link services: admin/guides/link_service.md
        - Common Assets: admin/guides/common_workspace_readonly.md
        - HTTP Mode: admin/guides/hosting_site_without_https.md
        - Basepath: admin/guides/update_basepath.md
  - User:
      - Motivation: user/motivation.md
      - Features: user/features.md
      - Website: user/website/index.md
      - Library: 
          - Assets: user/servers/lib/assets.md
          - Microservice: user/servers/lib/LIB-MS.md
      - Digital Twins: 
          - Create: user/digital-twins/create.md
          - Lifecycle: user/digital-twins/lifecycle.md
      - Runner: user/servers/execution/runner/README.md
      - Examples:
          - Overview: user/examples/index.md
          - Mass Spring Damper: user/examples/mass-spring-damper/README.md
          - Water Tank Fault Injection: user/examples/water_tank_FI/README.md
          - Water Tank Model Swap: user/examples/water_tank_swap/README.md
          - Desktop Robotti and RabbitMQ: user/examples/drobotti-rmqfmu/README.md
          - Water Plant and OPC-UA: user/examples/opc-ua-waterplant/README.md
          - Three Water Tanks: user/examples/three-tank/README.md
          - Flex Cell: user/examples/flex-cell/README.md
          - Incubator: user/examples/incubator/README.md
          - Firefighters: user/examples/o5g/README.md
          - Codebase: https://github.com/INTO-CPS-Association/DTaaS-examples
  - FAQ: FAQ.md
  - Developer: 
      - Overview: developer/index.md 
      - System:
        - Architecture: developer/system/architecture.md
        - Current Status: developer/system/current-status.md
      - Authorization: developer/oauth.md
      - Components:
        - Client: developer/client/client.md
        - Library Microservice: developer/servers/lib/lib-ms.md
      - Testing: developer/testing/intro.md
      - Publish NPM Packages: developer/npm-packages.md
  - Bugs: bugs.md
  - Thanks: thanks.md
  - License: 
      - DTaaS: LICENSE.md
      - Third Party: third-party.md 

use_directory_urls: false

extra_css:
  - assets/css/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true   
  - mdx_math:
      enable_dollar_delimiter: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - open-in-new-tab
  - search
  - with-pdf:
      author: "DTaaS Development Team"
      cover: true
      cover_logo: assets/dtaas-logo.png
      cover_subtitle: ""
      enabled_if_env: MKDOCS_ENABLE_PDF_EXPORT
      output_path: pdf/DTaaS-docs.pdf
