FROM node:20.10.0-slim

#! docker should be run from the root directory of the project

# Set the working directory inside the container
WORKDIR /dtaas/runner

# pull the libms package
RUN npm i -g @into-cps-association/runner@0.0.1

# Define the command to run your app
CMD ["runner"]
