GET http://localhost:5000 HTTP/1.1
content-type: application/json

###

GET http://localhost:5000/history HTTP/1.1
content-type: application/json

###

POST http://localhost:5000 HTTP/1.1
content-type: application/json

{
    "name": "create"
}

###

GET http://localhost:5000 HTTP/1.1
content-type: application/json

###

GET http://localhost:5000/history HTTP/1.1
content-type: application/json

###

POST http://localhost:5000 HTTP/1.1
content-type: application/json

{
    "name": "configure"
}

###

GET http://localhost:5000 HTTP/1.1
content-type: application/json

###

GET http://localhost:5000/history HTTP/1.1
content-type: application/json

###

POST http://localhost:5000 HTTP/1.1
content-type: application/json

{
    "command": "create"
}

###

GET http://localhost:5000 HTTP/1.1
content-type: application/json

###

GET http://localhost:5000/history HTTP/1.1
content-type: application/json
