type Node {
  name: String!
  type: String
  path: String
  rawBlob: String
  rawTextBlob: String
}

type Edge {
  node: Node!
}

type Blob {
  edges: [Edge!]
  nodes: [Node!]
}

type Tree {
  blobs: Blob
  trees: Blob
}

type Repository {
  tree(recursive: Boolean = false): Tree!
  blobs(paths: [String]): Blob!
}

type Project {
  repository: Repository
  fullPath: String!
}

type Query {
  project(fullPath: String!): Project!

  listDirectory(path: String!): Project!
  readFile(path: String!): Project!
}
