services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command: 
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=web-secure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${DTAAS_DIR}/deploy/docker/dynamic/tls.local.yml:/etc/traefik/dynamic/tls.yml"
      - "${DTAAS_DIR}/deploy/docker/certs:/etc/traefik-certs"
    networks:
      - frontend
      - users

  client:
    image: intocps/dtaas-web:latest
    restart: unless-stopped
    volumes:
      - "${DTAAS_DIR}/deploy/config/client/env.local.js:/dtaas/client/build/env.js"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=PathPrefix(`/`)"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.services.client.loadbalancer.server.port=4000"
    networks:
      - frontend

  user1:
    image: mltooling/ml-workspace-minimal:0.13.2
    restart: unless-stopped
    volumes:
      - "${DTAAS_DIR}/files/common:/workspace/common"
      - "${DTAAS_DIR}/files/${username1}:/workspace"
    environment:
      - AUTHENTICATE_VIA_JUPYTER=
      - WORKSPACE_BASE_URL=${username1}
    shm_size: 512m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u1.rule=PathPrefix(`/${username1}`)"
      - "traefik.http.routers.u1.tls=true"
    networks:
      - users

networks:
  frontend:
    name: dtaas-frontend
  users:
    name: dtaas-users
