services:
  traefik:
    image: traefik:v3.6.13
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.forwardedHeaders.insecure=true"
      - "--entrypoints.web.proxyProtocol.insecure=true"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  client:
    image: intocps/dtaas-web:1.0.2
    restart: unless-stopped
    volumes:
      - "./config/client.js:/dtaas/client/build/env.js"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.entryPoints=web"
      - "traefik.http.services.client.loadbalancer.server.port=4000"
      - "traefik.http.routers.client.rule=PathPrefix(`/`)"

  user:
    image: intocps/workspace:main-967bc10
    restart: unless-stopped
    volumes:
      - "./files/common:/workspace/common"
      - "./files/${DEFAULT_USER:-user1}:/workspace"
    environment:
      - MAIN_USER=${DEFAULT_USER:-user1}
    shm_size: "512m"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.entryPoints=web"
      - "traefik.http.routers.user.rule=PathPrefix(`/${DEFAULT_USER:-user1}`)"
