apiVersion: v1
kind: Service
metadata:
  name: dtaas-web-service
spec:
  type: NodePort
  selector:
    app: dtaas-web
  ports:
    - protocol: TCP
      port: 4000          # The port the Service listens on internally (clusterIP)
      targetPort: 4000  # The port the container is listening on
      nodePort: 30420   # The port opened on each Node (30000-32767 range)
