image: fedora:41

stages:
  - triggers

trigger_hello-world:
  stage: triggers
  trigger:
    include: digital_twins/hello-world/.gitlab-ci.yml
  rules:
    - if: '$DTName == "hello-world"'
      when: always
  variables:
    RunnerTag: $RunnerTag

trigger_mass-spring-damper:
  stage: triggers
  trigger:
    include: digital_twins/mass-spring-damper/.gitlab-ci.yml
  rules: 
    - if: '$DTName == "mass-spring-damper"'
      when: always
  variables:
    RunnerTag: $RunnerTag

