on:
    workflow_call:
      inputs:
        registry-url:
          required: true
          type: string
        project-path:
          required: true
          type: string
        node-version:
          required: true
          type: string
  
  jobs:
    build-frontend:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Setup node
          uses: actions/setup-node@v4
          with:
            node-version: ${{ inputs.node-version }}
            cache: "yarn"
            cache-dependency-path: "**/yarn.lock"
            always-auth: true
            registry-url: ${{ inputs.registry-url }}
  
        - name: Publish npm package
          run: |
            # copy README.md to project root
            cp ${{ inputs.project-path }}/README.md .
            cd ${{ inputs.project-path }}
            yarn install
            yarn build
            yarn publish --access public
  