# -*- mode: ruby -*-
# vi: set ft=ruby :

# Creates the base environment for running the DTaaS application

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
      
    config.vm.provider "virtualbox" do |vb|
      vb.name = "dtaas-mlworkspace"
      vb.memory = 16384
      vb.cpus = 8
    end
  
    config.vm.provision "shell", path: "provision.sh"
end

