services:
  logger-ms:
    build:
      context: ../../
      dockerfile: ./developer/logger.dockerfile
    volumes:
      - ./logger.yaml.sample:/dtaas/logger/logger.yaml
      - ./logs:/dtaas/logger/logs
    ports:
      - 4003:4003
