services:
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    volumes:
      - "./gitlab-runner:/etc/gitlab-runner:z"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    network_mode: host
