services:
  gitlab-runner:
    container_name: gitlab-runner
    # Runner image version is independent of the gitlab-ce image version
    image: gitlab/gitlab-runner:alpine-v17.5.3
    volumes:
      - "./runner-config.toml:/etc/gitlab-runner/config.toml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # For https://localhost or a self-signed cert with your server
      - "${DTAAS_DIR}/deploy/docker/certs/${SERVER_DNS}/fullchain.pem:/etc/gitlab-runner/certs/${SERVER_DNS}.crt:ro"
    network_mode: host
