version: '3'
services:
  mohamedtest:
    image: mltooling/ml-workspace-minimal:0.13.2
    restart: unless-stopped
    volumes:
    - C:\Users\Mohamed\DTaaS/files/common:/workspace/common
    - C:\Users\Mohamed\DTaaS/files/mohamedtest:/workspace
    environment:
    - AUTHENTICATE_VIA_JUPYTER=
    - WORKSPACE_BASE_URL=mohamedtest
    shm_size: 512m
    labels:
    - traefik.enable=true
    - traefik.http.routers.mohamedtest.entryPoints=web
    - traefik.http.routers.mohamedtest.rule=PathPrefix(`/mohamedtest`)
    - traefik.http.routers.mohamedtest.middlewares=traefik-forward-auth
    networks:
    - users
networks:
  users:
    name: dtaas-users
    external: true
