version: '3'
services:
  user3:
    image: mltooling/ml-workspace-minimal:0.13.2
    volumes:
      - ${DTAAS_DIR}/files/common:/workspace/common
      - ${DTAAS_DIR}/files/${username3}:/workspace
    environment:
      - AUTHENTICATE_VIA_JUPYTER=
      - WORKSPACE_BASE_URL=${username3}
    shm_size: 512m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.u3.entryPoints=web"
      - "traefik.http.routers.u3.rule=PathPrefix(`/${username3}`)"
      - "traefik.http.routers.u3.middlewares=traefik-forward-auth"