version: '3'

services:
  client:
    build: 
      context: ../
      dockerfile: ./docker/client.dockerfile
    labels:
      - "traefik.http.services.client.loadbalancer.server.port=4000"
    volumes:
      - "../client/config/dev.js:/dtaas/client/build/env.js"
  libms:
    build: 
      context: ../
      dockerfile: ./docker/libms.dockerfile
    labels:
      - "traefik.http.services.libms.loadbalancer.server.port=4001"
    volumes:
      - "../deploy/config/lib.docker:/dtaas/libms/.env"
      - "../files:/dtaas/libms/files"

  ml-workspace-user1:
    image: mltooling/ml-workspace-minimal:0.13.2
    container_name: ml-workspace-user1
    volumes:
      - "../files/user1:/workspace"
      - "../files/common:/workspace/common"
    environment:
      - AUTHENTICATE_VIA_JUPYTER
      - WORKSPACE_BASE_URL=user1
    shm_size: 512m

  traefik-gateway:
    image: traefik:v2.10
    container_name: traefik-gateway
    ports:
      - "80:80"
    volumes:
      - "../servers/config/gateway/traefik.yml:/etc/traefik/traefik.yml"
      - "../servers/config/gateway/auth:/etc/traefik/auth"
      - "../servers/config/gateway/dynamic/fileConfig.docker.yml:/etc/traefik/dynamic/fileConfig.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"