tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/traefik.cert.pem
        keyFile: /etc/traefik/certs/traefik-nopasswd.key.pem
  options:
    default:
      clientAuth:
        # in PEM format. each file can contain multiple CAs.
        caFiles:
          - /etc/traefik/certs/ca.cert.pem
        clientAuthType: RequireAndVerifyClientCert

http:
  routers:
    dtaas:
      entryPoints:
        - websecure
      rule: 'Host(`localhost`)'
      service: dtaas
      tls: true

    grafana:
      entryPoints:
        - websecure
      rule: 'Host(`vis.localhost`)'
      service: grafana
      tls: true

    dashboard:
      entryPoints:
        - websecure
      rule: 'Host(`gateway.localhost`)'
      service: api@internal
      tls: true

  services:
    dtaas:
      loadBalancer:
        servers:
          - url: "http://localhost:4000"

    grafana:
      loadBalancer:
        servers:
          - url: "http://localhost:3000"
