# Reference: https://docs.gitlab.com/ee/install/docker/installation.html
services:
  gitlab:
    image: 'gitlab/gitlab-ce:17.9.2-ce.0'
    container_name: gitlab
    restart: always
    hostname: ${HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${HOSTNAME}:${GITLAB_PORT}/gitlab'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        nginx['listen_port'] = 443
        nginx['ssl_certificate'] = "/certs/fullchain.pem"
        nginx['ssl_certificate_key'] = "/certs/privkey.pem"
        letsencrypt['enable'] = false
    ports:
      - '${GITLAB_PORT}:443'
      - '2424:22'
    volumes:
      - './config/gitlab:/etc/gitlab'
      - './log/gitlab:/var/log/gitlab'
      - './data/gitlab/data:/var/opt/gitlab'
      - './certs:/certs:ro'
    shm_size: '256m'
    networks:
      - platform-services

networks:
  platform-services:
    name: dtaas-services
