services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.forwardedHeaders.insecure=true"
      - "--entrypoints.web.proxyProtocol.insecure=true"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
      - users

  libms:
    image: intocps/libms:0.5.9
    restart: unless-stopped
    volumes:
      - ./files:/dtaas/libms/files
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.libms.loadbalancer.server.port=4001"
      - "traefik.http.routers.libms.rule=Host(`${SERVER_DNS}`)&&PathPrefix(`/lib`)"
      - "traefik.http.routers.libms.entryPoints=web"
      - "traefik.http.routers.libms.middlewares=traefik-forward-auth"
    networks:
      - frontend

  client:
    image: intocps/dtaas-web:1.0.1
    restart: unless-stopped
    volumes:
      - ./config/client/env.server.js:/dtaas/client/build/env.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.entryPoints=web"
      - "traefik.http.routers.client.middlewares=traefik-forward-auth"
      - "traefik.http.services.client.loadbalancer.server.port=4000"
      - "traefik.http.routers.client.rule=Host(`${SERVER_DNS}`)&&PathPrefix(`/`)"
    networks:
      - frontend

  user1:
    image: intocps/workspace:main-967bc10
    restart: unless-stopped
    volumes:
      - ./files/common:/workspace/common
      - ./files/${username1}:/workspace
    environment:
      - MAIN_USER=${username1}
    shm_size: "512m"
    cpus: 4
    mem_limit: "4G"
    pids_limit: 4960
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user1.entryPoints=web"
      - "traefik.http.routers.user1.rule=Host(`${SERVER_DNS}`)&&PathPrefix(`/${username1}`)"
      - "traefik.http.routers.user1.middlewares=traefik-forward-auth"
    networks:
      - users

  user2:
    image: intocps/workspace:main-967bc10
    restart: unless-stopped
    volumes:
      - ./files/common:/workspace/common
      - ./files/${username2}:/workspace
    environment:
      - MAIN_USER=${username2}
    shm_size: "512m"
    cpus: 4
    mem_limit: "4G"
    pids_limit: 4960
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user2.entryPoints=web"
      - "traefik.http.routers.user2.rule=Host(`${SERVER_DNS}`)&&PathPrefix(`/${username2}`)"
      - "traefik.http.routers.user2.middlewares=traefik-forward-auth"
    networks:
      - users

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:latest
    restart: unless-stopped
    volumes:
      - ./config/forward-auth/conf.server:/conf
    environment:
      - LOG_LEVEL=trace
      - DEFAULT_PROVIDER=generic-oauth
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=${OAUTH_URL}/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=${OAUTH_URL}/oauth/token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=${OAUTH_URL}/api/v4/user
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - PROVIDERS_GENERIC_OAUTH_SCOPE=read_user
      - SECRET=${OAUTH_SECRET}
      - INSECURE_COOKIE=true
      - CONFIG=/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redirect.entryPoints=web"
      - "traefik.http.routers.redirect.rule=Host(`${SERVER_DNS}`)&&PathPrefix(`/_oauth`)"
      - "traefik.http.routers.redirect.middlewares=traefik-forward-auth"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    networks:
      - frontend
      - users

networks:
  frontend:
    name: dtaas-frontend
  users:
    name: dtaas-users
