version: "3.8"

services:
  dtaas: # This container has extra dev tools (Python, Ruby etc)
    build:
      context: dtaas 
      dockerfile: Dockerfile
      args:
        - NODE_USER=node
    volumes:
      - ..:/workspaces/DTaaS:cached
      - client-node-modules:/workspaces/DTaaS/client/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=4096
    command: sleep infinity
    ports: 
      - "4000:4000"
      - "4001:4001"
      - "5000:5000"
      - "8000:8000"
    user: node
    init: true

  client: # This container is for the client app
    build:
      context: client 
      dockerfile: Dockerfile
      args:
        - NODE_USER=node
    volumes:
      - ..:/workspaces/DTaaS:cached
      - client-node-modules:/workspaces/DTaaS/client/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=4096
      - FAST_REFRESH=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - WATCHPACK_POLLING=true
      - BROWSER=none
      - TSC_COMPILE_ON_ERROR=true
      - ESLINT_NO_DEV_ERRORS=true
    command: sleep infinity 
    ports:
      - "4000:4000" # Client dev server
    user: node
    init: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  client-node-modules:
    name: client-node-modules 
