classDiagram
    class FilesResolver {
    -filesService: IFilesService
    +listDirectory(path: string): Promise<Project>
    +readFile(path: string): Promise<Project>
    }

    class FilesServiceFactory {
    -configService: ConfigService
    -gitlabFilesService: GitlabFilesService
    -localFilesService: LocalFilesService
    +create(): IFilesService
    }

    class GitlabFilesService {
    -configService: ConfigService
    -parseArguments(path: string): Promise<domain: string; parsedPath: string>
    -sendRequest(query: string): Promise<Project>
    -executeQuery(path: string, getQuery: QueryFunction): Promise<Project>
    +listDirectory(path: string): Promise<Project>
    +readFile(path: string): Promise<Project>
    }

    class LocalFilesService {
    -configService: ConfigService
    -getFileStats(fullPath: string, file: string): Promise<Project>
    +listDirectory(path: string): Promise<Project>
    +readFile(path: string): Promise<Project>
    }

    class ConfigService {
    +get(propertyPath: string): any
    }

    class IFilesService{
    listDirectory(path: string): Promise<Project>
    readFile(path: string): Promise<Project>
    }

    IFilesService <|-- FilesResolver: uses
    IFilesService <|.. GitlabFilesService: implements
    IFilesService <|.. LocalFilesService: implements
    IFilesService <|-- FilesServiceFactory: creates
    ConfigService <|-- FilesServiceFactory: uses
    ConfigService <|-- GitlabFilesService: uses
    ConfigService <|-- LocalFilesService: uses