http:
  routers:
    lib:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/lib`)'
      service: lib


  services:
    lib:
      loadBalancer:
        servers:
          - url: "http://localhost:3000"
