http:
  routers:
    lib:
      entryPoints:
        - http
      rule: "Host(`localhost`)"
      service: lib

  services:
    lib:
      loadBalancer:
        servers:
          - url: "http://localhost:4001"
