http:
  routers:
    dtaas:
      entryPoints:
        - http
      rule: 'Host(`localhost`)'
      service: dtaas

    aryanbhosale:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/aryanbhosale`)'
      service: aryanbhosale

    libms:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/lib`)'
      service: libms

  services:
    dtaas:
      loadBalancer:
        servers:
          - url: "http://localhost:4000"

    aryanbhosale:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"

    libms:
      loadBalancer:
        servers:
          - url: "http://localhost:4001"
