@startuml
class FilesResolver {
  -filesService: IFilesService
  +listDirectory(path: string): Promise<Project>
  +readFile(path: string): Promise<Project>
}

interface IFilesService {
  listDirectory(path: string): Promise<Project>
  readFile(path: string): Promise<Project>
}

class FilesServiceFactory {
  -configService: ConfigService
  -localFilesService: LocalFilesService
  +create(): IFilesService
}


class LocalFilesService {
  -configService: ConfigService
  -getFileStats(fullPath: string, file: string): Promise<Project>
  +listDirectory(path: string): Promise<Project>
  +readFile(path: string): Promise<Project>
}

class ConfigService {
  +get(propertyPath: string): any
}

FilesResolver --> IFilesService: uses
IFilesService <|.. LocalFilesService: implements
FilesServiceFactory --> IFilesService: creates
FilesServiceFactory --> ConfigService: uses
LocalFilesService --> ConfigService: uses
@enduml
