#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --cached --name-only | grep "^client/" >/dev/null; then
    cd client
    yarn format && yarn syntax
else
    echo "No changes in the client directory. Skipping pre-commit hook."
fi
