"""The 'platform' noun group: manage the installed core services as one unit.

'platform' names the running DTaaS instance's core services (traefik, client,
gitlab, ...) managed together: install, uninstall, update, and the lifecycle
verbs status/stop/start/pause/resume. Per-user containers are a separate axis,
managed individually via 'dtaas user ...' (see DTaaS-CLI-Design.md). The
lifecycle verbs live in cmd_lifecycle.py and are wired on below.
"""

import click
from python_on_whales.exceptions import DockerException
from .pkg import deploy as deployPkg
from .cmd_deploy_utils import provision_user_files
from .cmd_utils import (
    UpdateOptions,
    confirm_remove_user_files,
    run_uninstall,
    run_update,
)
from .cmd_lifecycle import add_lifecycle_commands
from .cmd_options import output_dir_option


@click.group(name="platform")
def platform_group():
    """Install, update, and operate the DTaaS core services as one unit.

    Generate and validate dtaas.toml with 'dtaas config ...' and the deployment
    files with 'dtaas deployment generate' first. These verbs act on the core
    services; manage additional users individually with 'dtaas user ...'.
    """


@platform_group.command(name="install")
@output_dir_option
def install(output_dir):
    """Start the deployment with 'docker compose up -d'.

    Requires a deployment generated by 'dtaas deployment generate'. Before
    starting, provisions per-user workspace directories for any users declared
    under [[users]] in dtaas.toml.

    Next: run 'dtaas user add' to add users to the running instance.
    """
    try:
        provision_user_files(output_dir)
        deployPkg.install(output_dir)
    except (OSError, DockerException) as exc:
        raise click.ClickException(str(exc)) from exc
    click.echo("Deployment installed successfully")


@platform_group.command(name="uninstall")
@output_dir_option
@click.option(
    "--remove-user-files",
    is_flag=True,
    help="Also delete per-user workspace files (destructive).",
)
@click.option(
    "--yes",
    "-y",
    is_flag=True,
    help="Skip the confirmation prompt for --remove-user-files.",
)
def uninstall(output_dir, remove_user_files, yes):
    """Stop and remove the whole installation with 'docker compose down'.

    Unlike 'platform stop'/'pause' (core services only), uninstall is
    whole-installation: it tears down the core services **and** every per-user
    container (compose.users.yml) so the shared network can be removed.

    Per-user workspace files are preserved by default. Use --remove-user-files
    to also delete the per-user workspace directories and the CLI-owned
    dtaas.users.registry.json / .dtaas.state.json (prompts for confirmation;
    skip with --yes in non-interactive scripts).
    """
    confirm_remove_user_files(remove_user_files, yes)
    run_uninstall(output_dir, remove_user_files)


@platform_group.command(name="update")
@click.option(
    "--certs",
    is_flag=True,
    help="Refresh the deployment's TLS certificates in place.",
)
@click.option(
    "--config",
    "config_",
    is_flag=True,
    help="Re-apply dtaas.toml config to all services in place.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="With --config, report what would change without applying it.",
)
@output_dir_option
def update(**kwargs):
    """Update deployment assets in place without regenerating the project.

    \b
    Examples:
      dtaas platform update --certs                  # rotate TLS certificates
      dtaas platform update --config                 # re-apply dtaas.toml
      dtaas platform update --config --dry-run       # preview changes first

    --certs swaps in the newest certificate pair from certs-src and reloads
    traefik. --config re-substitutes dtaas.toml into service config files
    and restarts services whose files changed.
    """
    run_update(UpdateOptions(**kwargs))


# Lifecycle verbs status/stop/start/pause/resume (defined in cmd_lifecycle.py)
add_lifecycle_commands(platform_group)
