
services:
  mongodb:
    image: 'mongo:8.0.3'
    container_name: mongodb
    restart: always
    command: mongod --config /etc/mongod.conf
    ports:
      - '${MONGODB_PORT}:27017'
    volumes:
      - './data/mongodb:/data/db'
      - './config/mongod.conf.secure:/etc/mongod.conf'
      - './certs/${HOSTNAME}/combined.pem:/etc/ssl/cert.pem'
    shm_size: '256m'
    networks:
      - platform-services

  grafana:
    image: 'grafana/grafana:11.3.4-ubuntu'
    container_name: grafana
    restart: always
    volumes:
      - './data/grafana:/var/lib/grafana'
    environment:
      GF_SERVER_DOMAIN: '${HOSTNAME}'
      HOME: '/home/grafana'
    networks:
      - platform-services


networks:
  platform-services:
    name: dtaas-platform-services
