---
name: Auto PR Comment

'on':
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    name: Post automatic comment on PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Post a comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @copilot review