# Reusable workflow for building a Docker image without pushing.
# Used to validate Dockerfiles on pull requests.

name: Build Docker Image

'on':
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        # v7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          lfs: false
          sparse-checkout: |
            client
            developer
            servers/lib

      - name: Setup node
        if: ${{ inputs.dockerfile == 'client.built.dockerfile' }}
        # v7.0.0
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 26
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install dependencies
        if: ${{ inputs.dockerfile == 'client.built.dockerfile' }}
        working-directory: client/
        run: |
          yarn install --network-timeout 1000000

      - name: Run the linting checks
        if: ${{ inputs.dockerfile == 'client.built.dockerfile' }}
        working-directory: client/
        run: |
          yarn syntax

      - name: Build the React SPA website and setup env
        if: ${{ inputs.dockerfile == 'client.built.dockerfile' }}
        working-directory: client/
        run: |
          yarn build
          yarn config:test

      - name: Build Docker image
        # v7.4.0
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc
        with:
          context: .
          file: ./developer/check/${{ inputs.dockerfile }}
          push: false
          tags: ${{ inputs.image-name }}:test
