name: Library microservice

on:
  push:
    paths:
      - 'servers/lib/**'
      - '.github/workflows/lib-ms.yml'
  pull_request:
    paths:
      - 'servers/lib/**'
      - '.github/workflows/lib-ms.yml'
  workflow_dispatch:

env:
  NODE_VERSION: 24
  HTTP_PORT: 4002
  LIBMS_CONFIG_PATH: test/libms.test.yaml

permissions:
  contents: read # ✅ Required for checking out the code

jobs:
  test-lib-ms:
    permissions:
      contents: read # ✅ Required for checking out the code
    name: Test library microservice
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: servers/lib

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install pm2 and jest
        run: |
          npm install -g pm2
          npm install -g jest

      - name: Run the linting checks and formatting
        run: |
          yarn install
          yarn syntax
          yarn format

      - name: Build the lib microservice
        run: |
          yarn build

      - name: Run all tests
        run: |
          yarn build
          yarn test:all

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de #v5.5.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: servers/lib/coverage/clover.xml
          flags: lib-microservice-tests

      - name: Update configuration
        env:
          LIBMS_LOCAL_PATH: ${{ github.workspace }}/files
          LIBMS_PORT: ${{ env.HTTP_PORT }}
        run: |
          node test/update-config.js  

      - name: Start http mode
        env: 
          LIBMS_CONFIG_PATH: ${{env.LIBMS_CONFIG_PATH}}
        run: |
          yarn build
          yarn start:pm2
      
      - name: Check server is running (Windows)
        if: runner.os == 'Windows'
        env:
          PORT: ${{ env.HTTP_PORT }}
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
        with:
          timeout_seconds: 10
          max_attempts: 4
          command: "Invoke-WebRequest -Uri http://localhost:${{ env.PORT }}/lib/files -Method Head -UseBasicParsing"

      - name: Check server is running (Linux)
        if: runner.os != 'Windows'
        env:
          PORT: ${{ env.HTTP_PORT }}
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 #v3.0.2
        with:
          timeout_seconds: 10
          max_attempts: 4
          command: "curl -f -LI http://localhost:${{ env.PORT }}/lib/files"

      - name: Run http test
        env:
          PORT: ${{ env.HTTP_PORT }}
          LOCAL_PATH: ${{ github.workspace }}/files
          MODE: local
          LOG_LEVEL: debug
          APOLLO_PATH: /lib
        run: |
          yarn test:http-github

      - name: Stop http mode
        run: |
          yarn stop:pm2
