name: Library microservice

on:
  push:
    paths:
      - "servers/lib/**"
  pull_request:
    paths:
      - "servers/lib/**"
  workflow_dispatch:
    paths:
      - "servers/lib/**"

jobs:
  test-lib-ms:
    name: Test library microservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Run the linting checks
        run: |
          cd servers/lib
          yarn install
          yarn syntax

      - name: Build the lib microservice
        run: |
          cd servers/lib	
          yarn install	
          yarn build

      - name: Run unit and integration tests
        run: |
          cd servers/lib
          yarn install
          yarn test -a
        env:
          PORT: 4001
          LOCAL_PATH: ${{ github.workspace }}/files
          GITLAB_GROUP: dtaas
          GITLAB_URL: https://gitlab.com/api/graphql
          TOKEN: token
          MODE: gitlab
          LOG_LEVEL: debug
          APOLLO_PATH: /lib

      - name: Upload unit and integration test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: servers/lib/coverage/clover.xml
          flags: lib-microservice-tests

  publish-package:
    if: |
      github.event_name == 'push' &&
      (startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/release-v'))

    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: test-lib-ms
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
          always-auth: true
          registry-url: "https://npm.pkg.github.com/"

      - name: Publish package
        run: |
          cd servers/lib
          yarn install
          yarn build
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
