name: Platform Services CLI

'on':
  push:
    tags:
      - 'dtaas-services-v*'
  pull_request:
    paths:
      - 'deploy/services/cli/**'
  workflow_dispatch:


jobs:
  test-services-cli:
    name: Test and Build Platform Services CLI
    permissions:
      contents: read  # Required for checking out the code
      actions: write  # Required for uploading artifacts
    uses: ./.github/workflows/python-reusable.yml
    with:
      working-directory: deploy/services/cli
      src-directory: dtaas_services
      tests-directory: tests
      coverage-file: deploy/services/cli/coverage.xml
      artifact-name: dtaas-cli
      artifact-path: |
        deploy/services/cli/dist/*.whl
        deploy/services/cli/dist/*.tar.gz
      run-pyright: true

  publish-services-cli:
    name: Publish Platform Services CLI to PyPI
    needs: [test-services-cli]
    if: startsWith(github.ref, 'refs/tags/dtaas-services-v')
    permissions:
      contents: read
    uses: ./.github/workflows/publish-pypi.yml
    with:
      working-directory: deploy/services/cli
      artifact-name: dtaas-cli
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
