name: Platform Services CLI

'on':
  push:
    tags:
      - 'dtaas-services-python-v*'
  pull_request:
    paths:
      - 'deploy/services/cli/**'
  workflow_dispatch:


jobs:
  test-services-cli:
    name: Test and Build Platform Services CLI
    permissions:
      contents: read  # Required for checking out the code
      actions: write  # Required for uploading artifacts
    uses: ./.github/workflows/python-reusable.yml
    with:
      working-directory: deploy/services/cli
      src-directory: dtaas_services
      tests-directory: tests
      coverage-file: deploy/services/cli/coverage.xml
      artifact-name: dtaas-cli
      run-pyright: true
      # yamllint disable-line rule:line-length
      publish: ${{ startsWith(github.ref, 'refs/tags/dtaas-services-python-v') }}
