name: CLI for DTaaS

'on':
  push:
    branches:
      - 'feature/distributed-demo'
    paths:
      - 'cli/**'
      - '.github/workflows/python-cli.yml'
  pull_request:
    paths:
      - 'cli/**'
      - '.github/workflows/python-cli.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-cli:
    name: Test and Build DTaaS CLI
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/python-reusable.yml
    with:
      working-directory: cli
      src-directory: src
      tests-directory: tests
      coverage-file: cli/coverage.xml
      artifact-name: dtaas-cli
      artifact-path: dist
      run-pyright: true
      run-build-script: true

  publish-pypi:
    name: Publish to PyPI
    needs: [test-cli]
    if: |
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      github.ref == 'refs/heads/feature/distributed-demo'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download dist artefacts
        # v8.0.1
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: dtaas-cli
          path: ./

      - name: Publish to PyPI
        # v1.14.0
        # yamllint disable-line rule:line-length
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
        with:
          packages-dir: .
