name: CLI for DTaaS

'on':
  push:
    branches:
      - 'feature/distributed-demo'
    paths:
      - 'cli/**'
      - '.github/workflows/python-cli.yml'
  pull_request:
    paths:
      - 'cli/**'
      - '.github/workflows/python-cli.yml'
  workflow_dispatch:

jobs:
  test-cli:
    name: Test and Build DTaaS CLI
    permissions:
      contents: read
      actions: write
    uses: ./.github/workflows/python-reusable.yml
    with:
      working-directory: cli
      src-directory: src
      tests-directory: tests
      coverage-file: cli/coverage.xml
      artifact-name: dtaas-cli
      run-pyright: true

  publish-pypi:
    name: Publish to PyPI
    needs: [test-cli]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download dist artefacts
        # v4.3.0
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: dtaas-cli
          path: ./

      - name: Publish to PyPI
        # v1.12.4
        # yamllint disable-line rule:line-length
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          packages-dir: .
