name: Release Packages

'on':
  push:
    paths:
      - 'deploy/dtaas/**'
      - 'deploy/workspace/**'
      - '.github/workflows/release-packages.yml'
  pull_request:
    paths:
      - 'deploy/dtaas/**'
      - 'deploy/workspace/**'
      - '.github/workflows/release-packages.yml'
  workflow_dispatch:


jobs:
  release-packages:
    name: Build and Upload Release Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout Repository
        # v6.0.1
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          lfs: false

      - name: Upload dtaas-localhost
        # v6.0.0
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: dtaas-localhost
          path: deploy/dtaas/docker/localhost
          if-no-files-found: error
          retention-days: 2

      - name: Upload dtaas-server
        # v6.0.0
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: dtaas-server
          path: deploy/dtaas/docker/server
          if-no-files-found: error
          retention-days: 2

      - name: Upload dtaas-secure-server
        # v6.0.0
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: dtaas-secure-server
          path: deploy/dtaas/docker/secure-server
          if-no-files-found: error
          retention-days: 2

      - name: Upload dtaas-secure-server-integrated-gitlab
        # v6.0.0
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: dtaas-secure-server-integrated-gitlab
          path: deploy/dtaas/docker/secure-server_with_integrated-gitlab
          if-no-files-found: error
          retention-days: 2

      - name: Upload workspace-dex-localhost
        # v6.0.0
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: workspace-dex-localhost
          path: deploy/workspace/dex/localhost
          if-no-files-found: error
          retention-days: 2

      - name: Upload workspace-keycloak-production
        # v6.0.0
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: workspace-keycloak-production
          path: deploy/workspace/keycloak/production
          if-no-files-found: error
          retention-days: 2
