name: Check the server microservices

on:
  push:
    branches: [development]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Run the linting checks
        run: |
          cd servers/lib
          yarn install
          yarn syntax

      - name: Run lib microservice tests
        run: |
          cd servers/lib
          yarn install
          yarn test

      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: servers/lib/coverage/clover.xml
          flags: lib-microservice
