name: Check the server microservices

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
    paths-ignore:
      - 'docs/**'

jobs:
  test-lib-ms:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Run the linting checks
        run: |
          cd servers/lib
          yarn install
          yarn syntax

      - name: Build the lib microservice
        run: |
          cd servers/lib	
          yarn install	
          yarn build

      - name: Run lib microservice tests
        run: |
          cd servers/lib
          yarn install
          yarn test -u
          yarn test -i
        env:
          PORT: 4001
          LOCAL_PATH: ${{ github.workspace }}/files
          GITLAB_GROUP: dtaas
          GITLAB_URL: https://gitlab.com/api/graphql
          TOKEN: token
          MODE: gitlab
          LOG_LEVEL: debug
          APOLLO_PATH: /lib
      - name: Upload unit, integration, and e2e test coverage for all to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: servers/lib/coverage/clover.xml
          flags: lib-microservice

  test-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Run the linting checks
        run: |
          cd sservers/execution/runner
          yarn install
          yarn syntax

      - name: Build the runner microservice
        run: |
          cd servers/execution/runner	
          yarn install	
          yarn build

      - name: Run runner microservice tests
        run: |
          cd servers/execution/runner
          yarn install
          yarn test -u
        env:
          PORT: 4001
          LOCAL_PATH: ${{ github.workspace }}/files
          GITLAB_GROUP: dtaas
          GITLAB_URL: https://gitlab.com/api/graphql
          TOKEN: token
          MODE: gitlab
          LOG_LEVEL: debug
          APOLLO_PATH: /lib
      - name: Upload test coverage of runner microservice to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: servers/execution/runner/coverage/clover.xml
          flags: runner-microservice
