# workflow that runs on this current branch


on:
  push:
    branches:
      - 381-create-docker-containers-for-client-lib-and-runner

jobs:
    get-version:
        name: Get version
        runs-on: ubuntu-latest
        steps:
            - name: Install jq
              run: sudo apt-get install -y jq
            - name: get version
              id: vars
              run: | 
                version=`cat ./client/package.json | jq -r '.version'`
                echo "version=$version" >> $GITHUB_OUTPUT
        outputs:
          version: ${{ steps.vars.outputs.version }}
    
    publish-docker-image:
        name: Publish Docker image
        needs: get-version
        uses: ./.github/workflows/docker.yml
        with: 
            registry: ghcr.io
            image-name: into-cps-association/test-image
            version: ${{ needs.get-version.outputs.version }}
            dockerfile: libms.dockerfile